// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uajrugrdboywbibxxfal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhanJ1Z3JkYm95d2JpYnh4ZmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTcxMjcsImV4cCI6MjA1ODM5MzEyN30.Jqh6ZVWYn6lUJEWh9P9Fxl5kJLMhoxnh62DKDyQQSZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);